version: '3.8'

services:
  streamlit-app:
    build: .
    ports:
      - "8509:8509"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_PORT=8509
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped 